version: '3.9'
services:
  pds:
    container_name: pds
    image: ghcr.io/bluesky-social/pds:latest
    networks:
      - web
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/docker-sky/pds
        target: /pds
    env_file:
      - /opt/docker-sky/pds/pds.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sky.rule=Host(`example.exe`)"
      - "traefik.http.routers.sky.tls=true"
      - "traefik.http.routers.sky.entrypoints=websecure,web"
      - "traefik.http.services.sky.loadbalancer.server.port=3000"
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: "@midnight"

networks:
  web:
    external: true
